# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 Noyalib. All rights reserved.

[package]
name = "noyalib-wasm-fuzz"
version = "0.0.0"
publish = false
edition = "2021"
license = "MIT OR Apache-2.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.noyalib-wasm]
path = ".."

[[bin]]
name = "fuzz_core"
path = "fuzz_targets/fuzz_core.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_document_path"
path = "fuzz_targets/fuzz_document_path.rs"
test = false
doc = false
bench = false
